### PR TITLE
Improving pod-template visualization

### PR DESCRIPTION
**Pull request by rhamilto**

### CODE REVIEW

**Comment by spadgett** [comment]
@jwforres @rhamilto Just noticed this, but I think the bold styles in the pod template give too much weight to the content. They draw your eye, and they aren't as important as other things on this page.

screenshot_3_23_16__4_59_pm

**Comment by rhamilto** [comment]
@spadgett, the font is wrong in your screenshot.  It should be Open Sans semi-bold, which doesn't look nearly so bold.

screen shot 2016-03-23 at 5 35 14 pm

**Comment by spadgett** [comment]
Do we know if that font is available on iOS?



    _____________________________

**Comment by rhamilto** [comment]
> Do we know if that font is available on iOS?

It's a web font from PatternFly.  It should be getting delivered to any/all browsers.

**Comment by spadgett** [comment]
OK, I'm seeing it now.

**Pull request merged**
